
---
- name: Creates /opt/elk/k8s/ directory
  become: yes
  file:
    path: /opt/elk/k8s
    state: directory

#copy j2 templates to /opt/elk/k8s/
- name: Copy deployment j2 template
  become: yes  
  template:
    src: "{{ item }}.j2"
    dest: "/opt/elk/k8s/{{ item }}"
  with_items:
    - "{{ logstash_config }}"

- name: Initiate logstash configmap
  become: yes
  shell: "kubectl apply -f /opt/elk/k8s/{{ item }}"
  with_items: 
    - "{{ logstash_config }}"

- name: wait for pods to come up
  shell: kubectl get pods -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
