apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /_cluster/health
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: elastic-config 
              mountPath: /etc/config/elasticsearch.yml
              subPath: elasticsearch.yml 
      volumes:
        - name: elastic-config
          configMap:
            name: elastic-config

        
