apiVersion: v1
kind: ConfigMap
metadata:
  name: log-manual-pipeline
  namespace: default
data:
  logstash.conf: |
    input {
      beats {
        port => "5044"
      }
    }
     
    output {
      elasticsearch {
        hosts => ["http://10.128.0.2:31455"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }      
